### ISSUE TITLE
argocd auth token has expired message appears even after logging in to argocd

### ISSUE THREAD

**Issue by jayanth-tjvrr** [arlonproj/arlon#353] opened 2022-12-08 12:19 UTC
Even after I login into argocd, below message still appears when I run any cluster commands. But all the argocd commands are working fine.

<img width="497" alt="image" src="https://user-images.githubusercontent.com/65030629/206444845-27dd1bdb-917f-43d7-bd98-ecb215456dc4.png">

**Comment by ShaunakJoshi1407** [comment] 2022-12-15 06:24
I am not able to reproduce this on my setup so far. Moving out of from 0.10 as it is not reproducible

**Comment by cruizen** [comment] 2023-01-12 21:28
Let's try to reproduce this - else we can close it and reopen if we encounter it again.

**Comment by ShaunakJoshi1407** [comment] 2023-01-18 09:36
Still not able to reproduce this issue. Let’s reopen this if we encounter this again

**Closed** 2023-01-20 08:17 UTC
Labels: bug, size:S
