### ISSUE TITLE
Arlon base cluster - Create EKS ClusterAPI Cluster

### ISSUE THREAD

**Issue by cre8minus1** [arlonproj/arlon#72] opened 2022-06-03 01:14 UTC
As a user of CluserAPI I would like to be able to template my clusters, store the template in Git and then use ArgoCD to create my Cluster.

So that my cluster infrastructure, and all associated Cluster API CRDs are managed ‘as-code’ in Git and if I choose, automatically updated/reverted using the ArgoCD continues Deployment ‘sync’ options.

**Comment by bcle** [comment] 2022-07-06 23:39
duplicate of #20

**Closed by bcle** 2022-07-06 23:39 UTC
Labels: duplicate, Approved, epic
