### ISSUE TITLE
Add `install` or `bootstrap` command to CLI to configure arlon on a management cluster

### ISSUE THREAD

**Issue by bcle** [arlonproj/arlon#3] opened 2022-01-24 14:21 UTC
It would at the minimum install the controller and CRD.

**Comment by cre8minus1** [comment] 2022-06-03 00:30
this is a potential duplicate of #4

**Comment by bcle** [comment] 2022-06-03 19:57
Agreed.

**Comment by cre8minus1** [comment] 2022-06-07 22:19
DUPLICATE

**Closed** 2022-06-07 22:19 UTC
Labels: duplicate, good first issue
